### ISSUE TITLE
h-links issue

### ISSUE THREAD

**Issue by randoomdude** [dnsev-h/x-links#3]
links don't convert to hoverible tags when getting new posts, only on refresh. Using ccd0's 4chan-x

**Comment by dnsev-h** [comment]
I've heard this is an issue but I have not experienced it myself.

Do you have any additional scripts enabled, and would you be willing to export your 4chan-x settings so that I may test with them?

**Comment by dnsev-h** [comment]
Just going to assume this has been fixed at this point, since so many changes have occurred since.

**Comment by dnsev-h** [comment]
For anyone who also gets this issue, try and give me the following information:

* Does an [Ex] tag appear next to links that don't work
* Are the links formatted with the gallery title, or is it still the URL

---

Also, open the dev console (CTRL+SHIFT+K in firefox, CTRL+SHIFT+J in chrome) and open the DOM inspector tab:

Right click the broken link and Inspect Element, and screencap the entire post's source in the DOM inspector ([see pic](https://cloud.githubusercontent.com/assets/10576365/10989927/868ed674-841b-11e5-97c1-86df76452e06.png)); start from a a line containing
```html
<div id="..." class="postContainer ...">
```
and continue til its closing `</div>` tag.

Should look like:
![dev](https://cloud.githubusercontent.com/assets/10576365/10989927/868ed674-841b-11e5-97c1-86df76452e06.png)

Additionally, if any of the x-links appearing in this view have the small `ev` bubble, click on them to show the events and screencap a pair of them as well. The tags should start with:

```html
<a class="xl-site-tag ...">
and
<a class="xl-link ...">
```

**Comment by shamoke** [comment]
You asked me to post here so as not to clutter the thread so here I am. Hopefully these screenshots give you the info you needed. I still have the old thread with the broken stuff open in case I missed anything or misunderstood.

There was an error when trying to attach the files so have an imgur gallery instead. http://imgur.com/a/sYoUc

**Comment by dnsev-h** [comment]
Alright thanks, everything you posted is more than I wanted.

From what it looks like, all of the links are formatted properly with the proper amount of events.

And so you say that hovering over these links did not create any details display?

**Comment by shamoke** [comment]
Yea hovering over the link does nothing at all. Opening the gallery works fine, and refreshing the thread fixes the no hover problem. Went through the latest 100+ posts in the recent thread and this is the only one that was broken.

![clipboard02](https://cloud.githubusercontent.com/assets/7976280/11004855/a22b54a8-8488-11e5-9714-870d67f85258.png)
![clipboard04](https://cloud.githubusercontent.com/assets/7976280/11004857/a8f5b300-8488-11e5-93e8-842502baf641.png)
![clipboard06](https://cloud.githubusercontent.com/assets/7976280/11004869/adb9fb12-8488-11e5-8e0c-2521fcaadd90.png)

That bottom ev looked the same as the last one so I posted the one right above it since it looks like it might be part of the same thing. Too big to screenshot the whole thing since I can't resize those little windows so hopefully I'm pasting it here properly.
```
var gallery_toggle_actions = function(event) {
  if ($.is_left_mouse(event) && config.actions.enabled) {
    event.preventDefault();

    var index = this.getAttribute("xl-actions-index"),
      actions, tag_bg, data, link, id;

    if (!index) {
      index = "" + actions_nodes_index;
      ++actions_nodes_index;
      this.setAttribute("xl-actions-index", index);
    }

    if (this.classList.toggle("xl-site-tag-active")) {
      // Create bg
      tag_bg = $(".xl-site-tag-bg", this);
      if (tag_bg === null) tag_bg = create_tag_bg(this);

      // Show
      actions = actions_nodes[index];
      if (actions !== undefined) {
        actions.classList.remove("xl-actions-hidden");
        Popup.hovering(actions);
        activate_actions(actions, index);
      } else {
        // Create
        if (
          (link = get_link_from_tag_button(this)) !== null &&
          (id = get_node_id(link)) !== null &&
          (data = API.get_data(id[0], id[1])) !== null
        ) {
          actions = create_actions(data, link, index);
          actions_nodes[index] = actions;
          activate_actions(actions, index);
        } else {
          return;
        }
      }

      // Position
      update_actions_position(actions, this, tag_bg, d.documentElement.getBoundingClientRect());
    } else {
      // Hide
      actions = actions_nodes[index];
      if (actions !== undefined) {
        close_actions(actions, index);
      }
    }
  }
}
```

Almost missed that last part, this is what happens when clicking on the [ex]
![clipboard08](https://cloud.githubusercontent.com/assets/7976280/11005319/0d895d38-848b-11e5-96e7-a1e8226a1d55.png)

**Comment by dnsev-h** [comment]
The source code of the events wasn't really necessary, I was more just interested in knowing if the events existed.

So it looks like the hovering elements aren't working properly. I'm hoping this is a styling issue.

Could you try doing the following?

* Open the DOM inspector and find an element that looks like:
  ```<div class="xl-hovering-elements">```
  It should appear very close to the bottom.

* Expand the node so you can see its children

* Hover over the broken link and see if any of them change. If one of them does, expand it. Screencap what you get.
  [example](https://cloud.githubusercontent.com/assets/10576365/11005904/a28bbfcc-848e-11e5-9d3d-354642406695.png)

* Additionally, if this node does exist, screencap the styles of that node on the right.
  [example](https://cloud.githubusercontent.com/assets/10576365/11005890/9751144a-848e-11e5-96b4-ebed17bb0802.png)

**Comment by shamoke** [comment]
Hovering over the broken link changes nothing in that area. Hovering over working links seems to highlight things in that area and they all appear to be in the order they were posted in the thread, so I hovered over the working links right above and below the broken one and there is nothing in between the 2 things that they highlighted.

![clipboard08](https://cloud.githubusercontent.com/assets/7976280/11007054/54a3eac6-8495-11e5-9c7f-35b80eab65e3.png)
![clipboard10](https://cloud.githubusercontent.com/assets/7976280/11007062/5bb7b298-8495-11e5-980c-5df2c67df801.png)
![clipboard12](https://cloud.githubusercontent.com/assets/7976280/11007067/607ef8a4-8495-11e5-9963-94ad9be35468.png)
![clipboard14](https://cloud.githubusercontent.com/assets/7976280/11007071/6642d828-8495-11e5-9bf0-b0ae53a4a90f.png)

**Comment by dnsev-h** [comment]
Okay that's odd. It seems that the nodes are either not being added to the page, or something is removing them.

Could you export your 4chan-x settings and post them here? (there's an "Export" link under the 4chan-x settings)

If that doesn't help me, I might have to whip up a version to debug this.

**Comment by shamoke** [comment]
https://mega.nz/#!ec8EhS6Q!953HK-6zc3QOfeTMrBojFcLRmfpK7YCEDMusnchqRaI

**Comment by dnsev-h** [comment]
Alright, I'll test with this for a bit to see if I can experience any problems.

**Comment by dnsev-h** [comment]
Okay so I've released a new version, [1.2.1](https://github.com/dnsev-h/x-links/tree/v1.2.1) which includes some debugging stuff related to the error you've been getting.

To enable, first update, then open settings and enable debugging (at the bottom.) Then reload whatever pages and wait until you get any more problems.

When you do, open the dev console again and check for any lines starting with either:
`X-links 1.2.1: Invalid link` or `X-links 1.2.1: Invalid details`
Next to this text, there should be some additional info that looks like `Object { ... }`
Click on the `Object` text to show the info in the side and expand as much as you can, ignoring anything named `__proto__` or is a dimmer color.

Screencap anything you get when this happens. Hopefully this should tell me what's going wrong and where. (It might not tell me why, but that's somewhat less important.)

**Comment by shamoke** [comment]
Is there something I'm missing that would let me expand everything at once and then copy the text? If I tried to expand everything within these even ignoring the proto stuff it would take several hours and be several hundred screenshots.

![clipboard16](https://cloud.githubusercontent.com/assets/7976280/11016666/180c8d12-8557-11e5-9faa-4bc26460c2a3.png)
![clipboard02](https://cloud.githubusercontent.com/assets/7976280/11016669/21e9d600-8557-11e5-9c65-a1ece9cbc135.png)
![clipboard04](https://cloud.githubusercontent.com/assets/7976280/11016670/256abbd2-8557-11e5-864c-7467b4252820.png)
![clipboard06](https://cloud.githubusercontent.com/assets/7976280/11016672/28f080d4-8557-11e5-9304-d86e2f1c2fe6.png)
![clipboard08](https://cloud.githubusercontent.com/assets/7976280/11016673/2c6a0d20-8557-11e5-90d8-5bf87a5b9171.png)
![clipboard10](https://cloud.githubusercontent.com/assets/7976280/11016674/30b4e1ca-8557-11e5-8578-48956572cba7.png)
![clipboard12](https://cloud.githubusercontent.com/assets/7976280/11016676/35064462-8557-11e5-9c62-b0e5df1fa881.png)
![clipboard14](https://cloud.githubusercontent.com/assets/7976280/11016677/3911498a-8557-11e5-91ff-77cdf002ec5f.png)

**Comment by dnsev-h** [comment]
Shoot, I should have clarified what to expand. I should have said I only needed the info one expanded.

The info you've provided me with basically tells me where the error is coming from, now I just have to figure out why. It seems to be an issue coming from the script not storing the gallery data properly.

One last thing that could help me: open up the dev console and copy and run this command:
```js
console.log(JSON.stringify(window.localStorage));
```

After running, press any `[…]` that appears to expand it fully, and copy it and paste it to a text file and upload. It will probably be fairly long.

Thank you for your cooperation, I hope to solve any issues you've been having soon.

**Comment by dnsev-h** [comment]
Actually, scratch that, I think I may have found where the issue is coming from. If this actually turns out to be where your problem is coming from, I feel like an idiot because it's such a simple fix.

**Comment by dnsev-h** [comment]
Alright, I have released [version 1.2.1.1](https://github.com/dnsev-h/x-links/tree/v1.2.1.1). Please update and let me know if you still experience any problems.

**Comment by shamoke** [comment]
Well I went through a full thread without it happening so it's probably fixed, but who knows since it only showed up at random before. Thanks for the support, I'll let you know if it comes back.

**Comment by dnsev-h** [comment]
It wasn't truly random before, it was because I was changing some things in the script that weren't outwardly visible. I might break it again in the future, but until then, I'll consider it fixed.
